// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, admin)
VALUES ($1, $2)
RETURNING id, name, admin
`

type CreateUserParams struct {
	Name  string
	Admin bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Admin)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Admin)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, name, admin
FROM users
WHERE name=$1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, name)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Admin)
	return i, err
}
